-- Migration V7: Superseded by V5 power-parameter refactor
--
-- V5 already replaces the legacy power columns by dropping cos_phi and
-- power_reactive, then adding:
-- - power_reactive_fund
-- - power_distortion
-- - power_factor
-- - phase_shift
--
-- Keep this version as a no-op so clean databases can migrate past V7 without
-- re-adding or renaming columns that no longer exist after V5.
