export const POWER_QUALITY_LIMITS = Object.freeze({
  VOLTAGE_CRITICAL_MIN: 207,
  VOLTAGE_CRITICAL_MAX: 253,
  VOLTAGE_WARNING_MIN: 220,
  VOLTAGE_WARNING_MAX: 240,
  FREQUENCY_CRITICAL_MIN: 49.5,
  FREQUENCY_CRITICAL_MAX: 50.5,
  FREQUENCY_WARNING_MIN: 49.8,
  FREQUENCY_WARNING_MAX: 50.2,
  CURRENT_WARNING: 13,
  CURRENT_CRITICAL: 16,
});